Repository GSA/Challenge_gov, pull requests merged in 2021-04, with the labels that each got.

#205 Fixes/permission and style around admin submission for solver
  assets/css/app/_base.scss
  lib/web/controllers/solution_controller.ex
  lib/web/router.ex
  lib/web/templates/solution/_form.html.eex
Labels: ready

#202 Refactor/code assessment and liveview porting
  assets/css/app/_base.scss
  lib/web/controllers/solution_controller.ex
  lib/web/router.ex
  lib/web/templates/solution/_form.html.eex
Labels: wip

#207 remove cents from prize amount
  lib/web/views/form_view.ex
Labels: ready

#209 Bugfix: no matching clause for solution controller new
  lib/web/controllers/solution_controller.ex
  test/web/controllers/solution_controller_test.exs
Labels: ready

#210 Solution form upload section: re-organize to match other places
  assets/js/app/_solution_file_upload.js
  lib/web/templates/solution/_form.html.eex
Labels: ready

#208 Update: allow edits on a published challenges not just published and OPEN
  lib/challenge_gov/challenges/challenge.ex
  test/challenge_gov/challenges/challenge_details_test.exs
Labels: updated & ready

#211 Chal 550/wysiwyg: linking and char limited version
  assets/css/app/_base.scss
  assets/js/app/_rich_text_editor.js
  lib/challenge_gov/challenges/challenge.ex
  lib/web/templates/challenge/review/_details.html.eex
  lib/web/templates/challenge/wizard/_details.html.eex
  lib/web/views/form_view.ex
  priv/repo/migrations/20210422044336_add_brief_description_delta_to_challenges.exs
Labels: updated & ready

#213 CHAL-549 Print view updates and automatic dialog box
  assets/client/src/components/ChallengeDetails.js
  assets/client/src/components/ChallengeTab.js
  assets/client/src/components/PreviewBanner.js
  assets/client/src/components/challenge_tabs/FAQ.js
  assets/client/src/components/challenge_tabs/HowToEnter.js
  assets/client/src/components/challenge_tabs/Judging.js
  assets/client/src/components/challenge_tabs/Overview.js
  assets/client/src/components/challenge_tabs/Prizes.js
  assets/client/src/components/challenge_tabs/Rules.js
  assets/client/src/components/challenge_tabs/Timeline.js
  assets/client/src/components/challenge_tabs/Winners.js
  assets/client/src/pages/PreviewPage.js
  assets/css/public/_details-page.scss
Labels: ready

#212 Chal 557 qa submission management process
  assets/css/app/_base.scss
  assets/js/app/_solution_file_upload.js
  lib/web/controllers/api/solution_document_controller.ex
  lib/web/templates/solution/_form.html.eex
  lib/web/views/phase_view.ex
Labels: ready

#214 Rewrite manage winners without liveview
  assets/js/app/_dynamic_nested_fields.js
  assets/js/app/_phase_winners_file_upload.js
  assets/js/app/index.js
  lib/challenge_gov/challenges/phase.ex
  lib/challenge_gov/phase_winners.ex
  lib/challenge_gov/phase_winners/phase_winner.ex
  lib/challenge_gov/phase_winners/winner.ex
  lib/challenge_gov/winners.ex
  lib/web/controllers/api/phase_winner_controller.ex
  lib/web/controllers/api/winner_controller.ex
  lib/web/controllers/phase_winner_controller.ex
  lib/web/live/phase_winners_live.ex
  lib/web/live/winners_live.ex
  lib/web/router.ex
  lib/web/templates/challenge/show.html.eex
  lib/web/templates/challenge/show/_other_actions.html.eex
  lib/web/templates/layout/live.html.leex
  lib/web/templates/layout/root.html.eex
  lib/web/templates/phase/_draft_winners_overview.html.leex
  lib/web/templates/phase/_individual_winner_form.html.leex
  lib/web/templates/phase/_individual_winner_show.html.leex
  lib/web/templates/phase/_review_winners_overview.html.leex
  lib/web/templates/phase/_winner_header.html.eex
  lib/web/templates/phase/draft_winners_individual.html.leex
  lib/web/templates/phase/winners.html.leex
  lib/web/templates/phase_winner/_form.html.eex
  lib/web/templates/phase_winner/edit.html.eex
  lib/web/templates/phase_winner/phase_selection.html.eex
  lib/web/templates/phase_winner/show.html.eex
  lib/web/templates/phase_winner/winners/_form.html.eex
  lib/web/views/api/phase_winner_view.ex
  lib/web/views/api/winner_view.ex
  lib/web/views/layout_view.ex
  lib/web/views/phase_winner_view.ex
  lib/web/views/shared_view.ex
  priv/repo/migrations/20210419200019_restructure_phase_winners_and_winners.exs
Labels: ready

#215 Fix managed submissions review checkboxes
  lib/challenge_gov/solutions.ex
  lib/challenge_gov/solutions/solution.ex
  lib/web/controllers/phase_controller.ex
  lib/web/templates/solution/_form.html.eex
  lib/web/templates/solution/index_managed.html.eex
  lib/web/templates/solution/show.html.eex
  test/web/controllers/solution_controller_test.exs
Labels: ready

#217 Added verify script and fixed Elixir warnings
  lib/challenge_gov/accounts.ex
  lib/challenge_gov/accounts/user.ex
  lib/challenge_gov/challenges/phases/winner.ex
  lib/challenge_gov/emails.ex
  lib/challenge_gov/phase_winners/phase_winner.ex
  lib/challenge_gov/solutions.ex
  lib/challenge_gov/winners.ex
  lib/web/controllers/api/solution_controller.ex
  lib/web/controllers/api/solution_document_controller.ex
  lib/web/controllers/phase_controller.ex
  lib/web/controllers/phase_winner_controller.ex
  lib/web/controllers/solution_controller.ex
  lib/web/views/api/solution_view.ex
  lib/web/views/challenge_view.ex
  lib/web/views/phase_view.ex
  lib/web/views/solution_view.ex
  verify.sh
Labels: ready

#218 Update javascript packages
  assets/yarn.lock
Labels: ready
