Repository GSA/Challenge_gov, pull requests merged in 2021-08, with the labels that each got.

#317 Updated message contexts for new scenarios
  lib/challenge_gov/messages/message_context.ex
  lib/web/views/message_context_view.ex
  priv/repo/migrations/20210726172128_change_message_context_audience_to_string.exs
  priv/repo/migrations/20210726174345_add_parent_to_message_contexts.exs
  test/challenge_gov/message_context_statuses_test.exs
  test/challenge_gov/message_contexts_test.exs
  test/challenge_gov/messages_test.exs
  test/support/test_helpers/message_context_status_helpers.ex
Labels: wip

#338 Tests and functions for message center permissions
  assets/yarn.lock
  lib/challenge_gov/challenges.ex
  lib/challenge_gov/message_contexts.ex
  lib/challenge_gov/messages.ex
  lib/web/controllers/api/message_controller.ex
  lib/web/controllers/message_context_controller.ex
  lib/web/views/api/message_view.ex
  test/challenge_gov/challenges/challenge_test.exs
  test/challenge_gov/message_contexts_test.exs
  test/challenge_gov/messages_test.exs
  test/support/test_helpers/message_context_status_helpers.ex
  test/web/controllers/api/message_controller_test.exs
  test/web/controllers/message_context_controller_test.exs
Labels: ready

#329 Chal 674/follow a challenge
  assets/css/app/_base.scss
  lib/challenge_gov/accounts.ex
  lib/web/controllers/challenge_controller.ex
  lib/web/templates/layout/app.html.eex
  test/web/controllers/challenge_controller_test.exs
Labels: ready

#328 Update follow challenge logos
  lib/web/templates/saved_challenge/_challenge_card.html.eex
  lib/web/templates/saved_challenge/new.html.eex
Labels: question

#339 Func to message multiple solvers for a challenge
  assets/js/app/_message_center.js
  lib/challenge_gov/message_context_statuses.ex
  lib/challenge_gov/message_contexts.ex
  lib/challenge_gov/submissions.ex
  lib/web/controllers/message_context_controller.ex
  lib/web/controllers/phase_controller.ex
  lib/web/router.ex
  lib/web/templates/message_context/new.html.eex
  lib/web/templates/message_context/new_multi_submission_message.html.eex
  lib/web/templates/message_context/show.html.eex
  lib/web/templates/phase/show.html.eex
  lib/web/templates/phase/submission_table/_content.html.eex
  lib/web/templates/phase/submission_table/_header.html.eex
  lib/web/templates/phase/submission_table/_table.html.eex
  lib/web/templates/shared/_pagination_post.html.eex
  lib/web/views/challenge_view.ex
  lib/web/views/message_context_view.ex
  lib/web/views/phase_view.ex
  lib/web/views/shared_view.ex
  test/challenge_gov/message_contexts_test.exs
  test/web/controllers/message_context_controller_test.exs
  test/web/views/message_context_view_test.exs
Labels: ready

#348 Fix message date sorting on message contexts
  lib/challenge_gov/message_contexts.ex
Labels: ready

#349 Fix message sorting to compare datetime
  lib/challenge_gov/message_contexts.ex
Labels: ready

#351 CHAL-680/Contexts for challenge owner group messaging
  lib/challenge_gov/message_context_statuses.ex
  lib/challenge_gov/message_contexts.ex
  lib/web/templates/message_context/new.html.eex
  test/challenge_gov/message_contexts_test.exs
  test/web/controllers/message_context_controller_test.exs
Labels: ready

#352 Change style on challenge file download to list
  assets/client/src/components/challenge_tabs/SectionResources.js
  assets/css/public/_challenge-tabs.scss
Labels: ready
