Repository GSA/Challenge_gov, pull requests merged in 2021-06, with the labels that each got.

#254 CHAL-622/Analytics V2 Updates
  assets/js/app/_analytics.js
  lib/challenge_gov/analytics.ex
  lib/web/controllers/analytics_controller.ex
  lib/web/templates/analytics/_filter.html.eex
  lib/web/templates/analytics/index.html.eex
  mix.exs
  mix.lock
Labels: wip

#252 Change submission sorting to be case insensitive, update default text,
  lib/challenge_gov/submissions.ex
  lib/web/templates/submission/edit.html.eex
  lib/web/templates/submission/show.html.eex
  lib/web/views/submission_view.ex
Labels: ready

#255 Bugfix: preload submitter on submission create(s) error cases
  lib/challenge_gov/submissions.ex
Labels: ready

#260 Submission form cancel button
  lib/web/templates/submission/_form.html.eex
  lib/web/templates/submission/edit.html.eex
  lib/web/templates/submission/new.html.eex
  lib/web/views/submission_view.ex
Labels: ready

#258 Chal 620/solver accept flows
  assets/client/src/components/ChallengeDetails.js
  assets/client/src/components/ChallengeTabs.js
  assets/client/src/pages/DetailsPage.js
  assets/client/src/routes/index.js
  lib/challenge_gov/submissions.ex
  lib/challenge_gov/submissions/submission.ex
  lib/web/controllers/dashboard_controller.ex
  lib/web/controllers/submission_controller.ex
  lib/web/router.ex
  lib/web/templates/email/managed-submission-created.html.eex
  lib/web/templates/submission/_form.html.eex
  lib/web/templates/submission/_unreviewed_submissions.html.eex
  lib/web/templates/submission/index.html.eex
  lib/web/views/submission_view.ex
  test/challenge_gov/submissions_test.exs
  test/support/test_helpers/submission_helpers.ex
  test/web/controllers/submission_controller_test.exs
Labels: question, ready

#259 Chal 620 - review verified
  lib/challenge_gov/submissions.ex
  lib/challenge_gov/submissions/submission.ex
  lib/web/controllers/submission_controller.ex
  lib/web/views/submission_view.ex
Labels: ready

#273 Chal 582/message center frontend
  assets/css/app/_message_center.scss
  assets/css/app/index.scss
  assets/js/app/_message_center.js
  assets/js/app/index.js
  lib/challenge_gov/accounts.ex
  lib/challenge_gov/message_context_statuses.ex
  lib/challenge_gov/message_contexts.ex
  lib/challenge_gov/messages.ex
  lib/challenge_gov/messages/message.ex
  lib/challenge_gov/messages/message_context.ex
  lib/challenge_gov/messages/message_context_status.ex
  lib/web/controllers/api/message_context_status_controller.ex
  lib/web/controllers/api/message_controller.ex
  lib/web/controllers/message_context_controller.ex
  lib/web/controllers/submission_controller.ex
  lib/web/router.ex
  lib/web/templates/layout/app.html.eex
  lib/web/templates/message_context/index.html.eex
  lib/web/templates/message_context/new.html.eex
  lib/web/templates/message_context/show.html.eex
  lib/web/views/api/message_context_status_view.ex
  lib/web/views/api/message_view.ex
  lib/web/views/layout_view.ex
  lib/web/views/message_context_view.ex
  priv/repo/migrations/20210608023340_setup_internal_messaging_framework.exs
  priv/repo/migrations/20210616032817_add_audience_to_message_context.exs
  test/challenge_gov/message_contexts_test.exs
  test/challenge_gov/messages_test.exs
Labels: ready

#277 Quick fix for duplicate message statuses on create
  lib/challenge_gov/message_context_statuses.ex
Labels: ready

#279 Added user names to messages
  assets/js/app/_message_center.js
  lib/challenge_gov/challenges/challenge.ex
  lib/challenge_gov/messages.ex
  lib/challenge_gov/winners.ex
  lib/web/controllers/api/winner_controller.ex
  lib/web/templates/message_context/show.html.eex
  lib/web/views/api/challenge_view.ex
  lib/web/views/api/message_view.ex
  lib/web/views/api/winner_view.ex
  lib/web/views/message_context_view.ex
Labels: ready

#281 Fixed messages always showing own username
  lib/challenge_gov/message_contexts.ex
  lib/web/templates/message_context/show.html.eex
Labels: ready
